name: application
description: "A new Flutter project with best iOS support and performance."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  lottie: ^3.3.1
  fl_chart: ^1.0.0
  intl: ^0.19.0
  flutter_svg: ^2.2.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.3
  tabler_icons: ^2.5.0+1

  # TTS and WebView
  flutter_tts: ^4.2.3
  flutter_inappwebview: ^6.0.0

  # New Additions
  connectivity_plus: ^6.1.4
  dio: ^5.9.0
  get_it: ^7.6.7
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.27
  overlay_support: ^2.1.0
  country_code_picker: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.6.0
  isar_generator: ^3.1.0
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  
dependency_overrides:
  js: ^0.7.2
  analyzer: ^8.0.0
  build: ^3.0.0
  build_runner_core: ^9.2.0
  source_gen: ^3.0.0
  dart_style: ^3.1.1
  petitparser: ^7.0.0
  rxdart: ^0.28.0
  material_color_utilities: ^0.13.0
  xml: ^6.6.0
  vector_math: ^2.2.0
  meta: ^1.17.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/raalc_golden_logo.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/images/raalc_golden_logo.webp
    - assets/images/test1.webp
    - assets/images/test2.webp
    - assets/images/test3.webp
    - assets/images/white_logo.webp
    - assets/images/arrow-big-right-line.svg
    - assets/images/RAALC Golden Circle transparent - HQ.png
    - assets/images/otp_image.svg


    - assets/animations/Logo.json
 

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Poppins/Poppins-ExtraBold.ttf
          weight: 800

    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/static/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/Montserrat/static/Montserrat-ExtraBold.ttf
          weight: 800
      
   